using System;
using System.Collections.Generic;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Windows.Forms;
using PKHeX.Core;

namespace PKHEdit;

/// <summary>Views a PKH (HOME) file, updates it from dropped PKMs, and exports its stored versions.</summary>
public partial class PKHEditor : Form
{
    private const string BaseTitle = "PKH Editor";

    /// <summary>When true, the import report dialog is shown for every import. Set to false to restore
    /// the original gate (only for Block/Confirm items; pure conversions applied directly with the
    /// report in the status tooltip) — that condition is still in place, just short-circuited.</summary>
    private const bool AlwaysShowImportDialog = true;

    /// <summary>Designer text of L_Status; restored by the Close button so the window looks freshly opened again.</summary>
    private const string InitialStatus = "Drop a .pkh file to open it, or a PKM file to create or update a PKH. Drag the sprite out to export.";

    private readonly IPKMView edit;
    private readonly ISaveFileProvider saveProvider;
    private readonly Font monoFont;

    private PKH? pkh;
    private string? filePath;
    private bool dirty;
    private bool loading;
    private HomeGameDataFormat selected;

    private Rectangle dragBox = Rectangle.Empty;
    private HomeForm? homeForm;

    public PKHEditor(IPKMView edit, ISaveFileProvider saveProvider)
    {
        InitializeComponent();
        this.edit = edit;
        this.saveProvider = saveProvider;
        monoFont = new Font(FontFamily.GenericMonospace, Font.Size);
        Disposed += (_, _) =>
        {
            monoFont.Dispose();
            ClearVersionCards();
            PB_Sprite.Image?.Dispose();
        };

        CB_CreateFormat.Items.AddRange(PkhService.ExportFormats.Cast<object>().ToArray());
        if (CB_CreateFormat.Items.Count != 0)
            CB_CreateFormat.SelectedIndex = 0;
        CB_Gender.Items.AddRange(new object[] { "♂", "♀", "-" }); // Gender byte 0/1/2
        toolTip1.SetToolTip(NUD_Level, "Level 1-100. Changing it sets EXP to that level's threshold; changing EXP updates the level.");
        DragEnter += OnDragEnter;
        DragDrop += OnDragDrop;
        SetupSpriteDragOut();
        toolTip1.SetToolTip(TB_Tracker, "HOME tracker (16 hex digits). Trackers starting with FFFF were generated by this plugin.");
        toolTip1.SetToolTip(PB_Sprite, "Drag out to export this PKH as a .pkh file. Drop a .pkh here to open it, or a PKM to update/create one.");
        toolTip1.SetToolTip(B_Home, "HOME storage: .pkh boxes kept in the Home folder next to PKHeX.");
        toolTip1.SetToolTip(CHK_UseCustomTracker, "On: identity uses the HOME tracker and Gen can make one. Off: no random trackers; identity by EC/ID32/OT fallback (tracker conflicts still warn).");
        toolTip1.SetToolTip(B_ClearTracker, "Clear the HOME tracker (set to 0).");
        CHK_UseCustomTracker.Checked = HomeStorage.GetUseCustomTracker(); // restored before the first RefreshAll
        RefreshAll();
    }

    #region Display

    private void RefreshAll()
    {
        loading = true;
        try
        {
            RefreshNatureItems(); // localized names in enum order; rebuilt so a language switch is picked up
            bool has = pkh != null;
            TC_Info.Enabled = has;
            bool readOnly = pkh != null && PkhService.HasPC9(pkh);
            TB_Nickname.ReadOnly = readOnly;
            NUD_EXP.Enabled = NUD_Level.Enabled = NUD_Friendship.Enabled = CB_Nature.Enabled = CB_StatAlignment.Enabled = CB_Gender.Enabled = TB_Tracker.Enabled = has && !readOnly;
            CB_CreateFormat.Enabled = B_CreateVersion.Enabled = has && !readOnly;
            B_Save.Enabled = B_Close.Enabled = has;
            B_ClearTracker.Enabled = has && !readOnly;
            // Random tracker generation only exists in custom-tracker mode.
            B_NewTracker.Enabled = has && !readOnly && CHK_UseCustomTracker.Checked;

            if (pkh == null)
            {
                GB_Main.Text = "PKH";
                TB_Name.Text = TB_Tracker.Text = TB_Nickname.Text = L_Ids.Text = TB_VersionInfo.Text = "";
                TB_Main.Text = TB_Met.Text = TB_Stat.Text = TB_Cosmetic.Text = TB_Other.Text = "";
                CB_Gender.SelectedIndex = -1;
                SetSprite(PB_Sprite, null);
                ClearVersionCards();
                UpdateTitle();
                return;
            }

            var versions = PkhService.GetVersions(pkh);
            if (!versions.Contains(selected))
                selected = versions.Count != 0 ? versions[0] : HomeGameDataFormat.None;

            GB_Main.Text = readOnly ? "PKH (read-only: contains Champions data)" : "PKH";
            TB_Name.Text = PkmUtil.GetDisplayName(pkh);
            TB_Tracker.Text = pkh.Tracker.ToString("X16");
            // PKH.Checksum is always 0 (RefreshChecksum is a no-op on PKH); show the selected version's exported checksum instead.
            // The sample export also feeds location/ball names (real Version+Context) and the Stats tab's calculated stats.
            PKM? sample = selected != HomeGameDataFormat.None ? PkhService.Export(pkh, selected) : null;
            var chk = sample != null ? PkmUtil.GetFileNameChecksum(sample).ToString("X4") : "----";
            L_Ids.Text = $"CHK {chk}   PID {pkh.PID:X8}   EC {pkh.EncryptionConstant:X8}";
            TB_Nickname.Text = pkh.Nickname;
            NUD_EXP.Value = Math.Min(NUD_EXP.Maximum, pkh.EXP);
            NUD_Level.Value = Math.Clamp((int)pkh.CurrentLevel, 1, 100);
            CB_Gender.SelectedIndex = pkh.Gender <= 2 ? pkh.Gender : -1;
            CB_Nature.SelectedIndex = (int)pkh.Nature <= (int)Nature.Quirky && (int)pkh.Nature < CB_Nature.Items.Count ? (int)pkh.Nature : -1;
            CB_StatAlignment.SelectedIndex = (int)pkh.StatAlignment <= (int)Nature.Quirky && (int)pkh.StatAlignment < CB_StatAlignment.Items.Count ? (int)pkh.StatAlignment : -1;
            NUD_Friendship.Value = pkh.CurrentFriendship;
            TB_Main.Text = GetMainText(pkh);
            TB_Met.Text = GetMetText(pkh, sample);
            TB_Stat.Text = GetStatText(pkh, sample);
            TB_Cosmetic.Text = GetCosmeticText(pkh);
            TB_Other.Text = GetOtherText(pkh);

            RefreshVersionCards(versions);
            RefreshSelectedVersion();
            UpdateTitle();
        }
        finally
        {
            loading = false;
        }
        AutoUpdateCurrentHandler(); // rule 4: re-judge after (re)selection, import or load; no-op when settled
    }

    // Combo holds GameInfo's localized nature names in Nature-enum order, so the selected index IS the
    // enum value. Rebuilt on every refresh; a corrupt index (out-of-range enum) falls back to no selection.
    // Both Nature and Stat alignment use the same table (StatAlignment is itself a Nature value).
    private void RefreshNatureItems()
    {
        var names = GameInfo.Strings.Natures;
        int count = Math.Min((int)Nature.Quirky + 1, names.Count);
        CB_Nature.Items.Clear();
        CB_StatAlignment.Items.Clear();
        for (int i = 0; i < count; i++)
        {
            CB_Nature.Items.Add(names[i]);
            CB_StatAlignment.Items.Add(names[i]);
        }
    }

    /// <summary>Shared/core data only (PKH.Main-page equivalent): no version-block fields here —
    /// ball, met location and moves live in the per-version data and are shown on Met/Version data.</summary>
    private static string GetMainText(PKH p)
    {
        var sb = new StringBuilder();
        var speciesTable = GameInfo.Strings.Species;
        string species = p.Species < speciesTable.Count ? speciesTable[p.Species] : p.Species.ToString(CultureInfo.InvariantCulture);
        string gender = p.Gender == 0 ? "♂" : p.Gender == 1 ? "♀" : "-";
        sb.AppendLine($"Species: {species} ({p.Species})   Form: {p.Form}");
        sb.AppendLine($"Nickname: {p.Nickname}   Nicknamed: {p.IsNicknamed}   Gender: {gender}");
        sb.AppendLine($"Level: {p.CurrentLevel}   EXP: {p.EXP}   Nature: {NatureName(p.Nature)}   Stat alignment: {NatureName(p.StatAlignment)}");
        sb.AppendLine($"Held item (HOME): {ItemName(p.HeldItem)}   Language: {LanguageName(p, p.Language)}");
        sb.AppendLine($"PID: {p.PID:X8}   EC: {p.EncryptionConstant:X8}   Shiny: {p.IsShiny}   Egg: {p.IsEgg}");
        sb.AppendLine($"Favorite: {p.Favorite}   Bad egg: {p.IsBadEgg}   Form argument: {p.FormArgument}");
        return sb.ToString();
    }

    /// <summary>Met-page content. MetLevel/MetDate/Fateful are core (shared); ball/locations live in
    /// the selected version's block, so they render from the sample export (null = no version data).</summary>
    private static string GetMetText(PKH p, PKM? sample)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"Origin game: {GameInfo.GetVersionName(p.Version)}   Battle version: {BattleVersionName(p.BattleVersion)}");
        sb.AppendLine($"Met level: {p.MetLevel}   Met date: 20{p.MetYear:00}-{p.MetMonth:00}-{p.MetDay:00}");
        if (p.EggYear != 0)
            sb.AppendLine($"Egg date: 20{p.EggYear:00}-{p.EggMonth:00}-{p.EggDay:00}");
        sb.AppendLine($"Fateful: {p.FatefulEncounter}");
        if (sample != null)
        {
            string ball = PkhService.ReadableValue("Ball", sample.Ball.ToString(CultureInfo.InvariantCulture), sample) ?? sample.Ball.ToString(CultureInfo.InvariantCulture);
            sb.AppendLine($"Ball: {ball}   Met location: {LocationText("MetLocation", sample.MetLocation, sample)}   Egg location: {LocationText("EggLocation", sample.EggLocation, sample)}");
        }
        else
        {
            sb.AppendLine("Ball: -   Met location: -   Egg location: - (no version data)");
        }
        return sb.ToString();
    }

    /// <summary>Stats-page content: IVs/EVs/hyper train are core; calculated stats come from the
    /// sample export (real PKM implements hyper-train-aware stat calculation; PKH itself does not).</summary>
    private static string GetStatText(PKH p, PKM? sample)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"IVs: {p.IV_HP}/{p.IV_ATK}/{p.IV_DEF}/{p.IV_SPA}/{p.IV_SPD}/{p.IV_SPE}   Hyper trained: {HyperTrainedText(p)}");
        sb.AppendLine($"EVs: {p.EV_HP}/{p.EV_ATK}/{p.EV_DEF}/{p.EV_SPA}/{p.EV_SPD}/{p.EV_SPE}");
        sb.AppendLine($"Current HP: {p.Stat_HPCurrent}   Status: 0x{p.Status_Condition:X8}");
        if (sample != null)
        {
            try
            {
                var stats = sample.GetStats(sample.PersonalInfo); // H/A/B/S/C/D
                sb.AppendLine($"Stats: HP {stats[0]}   ATK {stats[1]}   DEF {stats[2]}   SPA {stats[4]}   SPD {stats[5]}   SPE {stats[3]}");
            }
            catch (Exception)
            {
                sb.AppendLine("Stats: -"); // unmapped species/form personal entry
            }
        }
        return sb.ToString();
    }

    /// <summary>Cosmetic-page content (all core): scale scalars, markings, ribbons/marks, contest.</summary>
    private static string GetCosmeticText(PKH p)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"Height/Weight scalar: {p.HeightScalar} / {p.WeightScalar}");
        sb.AppendLine($"Markings: 0x{p.MarkingValue:X4}");
        sb.AppendLine($"Ribbons: {p.RibbonCount}   Marks: {p.MarkCount}");
        AppendRibbonDetail(sb, p);
        sb.AppendLine($"Contest: {p.ContestCool}/{p.ContestBeauty}/{p.ContestCute}/{p.ContestSmart}/{p.ContestTough} sheen {p.ContestSheen}");
        return sb.ToString();
    }

    private static string LocationText(string key, int raw, PKM? sample)
    {
        string id = raw.ToString(CultureInfo.InvariantCulture);
        return PkhService.ReadableValue(key, id, sample) is { } name ? $"{raw} ({name})" : id;
    }

    private static string GetOtherText(PKH p)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"OT: {p.OriginalTrainerName} ({(p.OriginalTrainerGender == 0 ? "♂" : "♀")})   ID: {p.DisplayTID:D6} / {p.DisplaySID:D4}");
        sb.AppendLine($"OT friendship: {p.OriginalTrainerFriendship}");
        sb.AppendLine($"OT memory: {p.OriginalTrainerMemory} (intensity {p.OriginalTrainerMemoryIntensity}, feeling {p.OriginalTrainerMemoryFeeling}, var {p.OriginalTrainerMemoryVariable})");
        sb.AppendLine();
        sb.AppendLine(p.IsUntraded ? "HT: (none)" : $"HT: {p.HandlingTrainerName} ({(p.HandlingTrainerGender == 0 ? "♂" : "♀")}), language {LanguageName(p, p.HandlingTrainerLanguage)}");
        sb.AppendLine($"HT friendship: {p.HandlingTrainerFriendship}   Current handler: {(p.CurrentHandler == 0 ? "OT" : "HT")}");
        sb.AppendLine($"HT memory: {p.HandlingTrainerMemory} (intensity {p.HandlingTrainerMemoryIntensity}, feeling {p.HandlingTrainerMemoryFeeling}, var {p.HandlingTrainerMemoryVariable})");
        sb.AppendLine();
        sb.AppendLine($"PKH data version: {p.DataVersion}   Stored versions: {string.Join(", ", PkhService.GetVersions(p))}{(PkhService.HasPC9(p) ? ", PC9" : "")}");
        return sb.ToString();
    }

    /// <summary>Localized language name from PKHeX's own table (GameInfo.LanguageDataSource), matched by
    /// LanguageID value: the entity's generation list first, then the widest list, then the enum name.</summary>
    private static string LanguageName(PKM p, int language)
    {
        if (language == 0)
            return "-";
        return FindLanguage(GameInfo.LanguageDataSource(p.Generation, p.Context), language)
            ?? FindLanguage(GameInfo.LanguageDataSource(9, EntityContext.Gen9a), language)
            ?? ((LanguageID)language).ToString();
    }

    private static string? FindLanguage(IReadOnlyList<ComboItem> list, int language)
    {
        foreach (var z in list)
        {
            if (z.Value == language)
                return z.Text;
        }
        return null;
    }

    /// <summary>Battle version: GameVersion.Any (= 0) means unset; known ids resolve to display names.</summary>
    private static string BattleVersionName(GameVersion battleVersion) =>
        battleVersion == GameVersion.Any ? "-" : GameInfo.GetVersionName(battleVersion);

    /// <summary>Hyper Training ("能力调整") as trained stat names in IV display order; "-" when none.</summary>
    private static string HyperTrainedText(PKH p)
    {
        var list = new List<string>();
        if (p.HT_HP) list.Add("HP");
        if (p.HT_ATK) list.Add("ATK");
        if (p.HT_DEF) list.Add("DEF");
        if (p.HT_SPA) list.Add("SPA");
        if (p.HT_SPD) list.Add("SPD");
        if (p.HT_SPE) list.Add("SPE");
        return list.Count == 0 ? "-" : string.Join(", ", list);
    }

    /// <summary>Localized nature name for a StatAlignment value (which is itself a Nature); raw id when unknown.</summary>
    private static string NatureName(Nature nature)
    {
        var names = GameInfo.Strings.Natures;
        int i = (int)nature;
        return i >= 0 && i < names.Count ? names[i] : i.ToString(CultureInfo.InvariantCulture);
    }

    /// <summary>Held item with PKHeX's localized name and id; "-" when none, raw id if outside the table.</summary>
    private static string ItemName(int item)
    {
        if (item == 0)
            return "-";
        var items = GameInfo.Strings.Item;
        return item > 0 && item < items.Count ? $"{items[item]} ({item})" : item.ToString(CultureInfo.InvariantCulture);
    }

    /// <summary>
    /// Lists the ribbons/marks actually set on the PKH with PKHeX's localized names. The flag
    /// properties live on PKH.Core (GameDataCore implements the IRibbonSet* interfaces; PKH itself only
    /// forwards the counts, which is why RibbonInfo.GetRibbonInfo(pkh) finds nothing), so they are
    /// enumerated there with PKHeX's own rules — prefix RibbonInfo.PropertyPrefix, bool = flag,
    /// byte = counter — and named via RibbonStrings.
    /// </summary>
    private static void AppendRibbonDetail(StringBuilder sb, PKH p)
    {
        var ribbons = new List<string>();
        var marks = new List<string>();
        var counters = new List<string>();
        try
        {
            var core = p.Core;
            foreach (var pi in core.GetType().GetProperties(BindingFlags.Public | BindingFlags.Instance))
            {
                if (!pi.Name.StartsWith(RibbonInfo.PropertyPrefix, StringComparison.Ordinal) || pi.GetIndexParameters().Length != 0)
                    continue;
                var value = pi.GetValue(core);
                if (value is bool flag && flag)
                {
                    // SWSH/SV marks live in the same ribbon block — PKHeX names them RibbonMark*.
                    string display = GameInfo.Strings.Ribbons.GetNameSafe(pi.Name, out var name) ? name : pi.Name;
                    if (pi.Name.StartsWith("RibbonMark", StringComparison.Ordinal))
                        marks.Add(display);
                    else
                        ribbons.Add(display);
                }
                else if (value is byte count && count != 0)
                {
                    string display = GameInfo.Strings.Ribbons.GetNameSafe(pi.Name, out var name) ? name : pi.Name;
                    counters.Add($"{display} {count}");
                }
            }
        }
        catch (Exception)
        {
            return; // counts line above still stands if reflection is unavailable
        }
        if (ribbons.Count != 0)
            sb.AppendLine($"Ribbons ({ribbons.Count}): {string.Join(", ", ribbons)}");
        if (marks.Count != 0)
            sb.AppendLine($"Marks ({marks.Count}): {string.Join(", ", marks)}");
        if (counters.Count != 0)
            sb.AppendLine($"Ribbon counters: {string.Join(", ", counters)}");
    }

    private void UpdateTitle()
    {
        var name = filePath != null ? Path.GetFileName(filePath) : pkh != null ? "(unsaved)" : null;
        Text = name == null ? BaseTitle : $"{BaseTitle} - {name}{(dirty ? " *" : "")}";
    }

    private static void SetSprite(PictureBox pb, PKM? pk)
    {
        var old = pb.Image;
        pb.Image = pk != null ? PKMSprite.Render(pk) : null;
        old?.Dispose();
    }

    #endregion

    #region Version cards

    private void ClearVersionCards()
    {
        foreach (Control c in FLP_Versions.Controls)
        {
            if (c is Panel { Tag: HomeGameDataFormat } card)
            {
                foreach (var pb in card.Controls.OfType<PictureBox>())
                    pb.Image?.Dispose();
            }
            c.Dispose();
        }
        FLP_Versions.Controls.Clear();
    }

    private void RefreshVersionCards(IReadOnlyList<HomeGameDataFormat> versions)
    {
        FLP_Versions.SuspendLayout();
        try
        {
            ClearVersionCards();
            foreach (var format in versions)
                FLP_Versions.Controls.Add(CreateCard(format));
        }
        finally
        {
            FLP_Versions.ResumeLayout();
        }

        RefreshMainSprite();
    }

    // Version selection (which stored version the sprite shows) lives in PkhService.GetPreferredFormat now,
    // so the HOME window can pick sprites the same way.
    private void RefreshMainSprite()
    {
        if (pkh == null)
        {
            SetSprite(PB_Sprite, null);
            return;
        }

        var format = PkhService.GetPreferredFormat(pkh, saveProvider.SAV.PKMType);
        SetSprite(PB_Sprite, format != HomeGameDataFormat.None ? PkhService.Export(pkh, format) : null);
    }

    // The main sprite drags out the whole PKH (not a single version's PKM) — Save/Open/editor import/export are
    // all covered by drag-and-drop, so the equivalent toolbar buttons were removed.
    private void SetupSpriteDragOut()
    {
        PB_Sprite.MouseDown += (_, e) =>
        {
            var size = SystemInformation.DragSize;
            dragBox = e.Button == MouseButtons.Left ? new Rectangle(e.X - (size.Width / 2), e.Y - (size.Height / 2), size.Width, size.Height) : Rectangle.Empty;
        };
        PB_Sprite.MouseUp += (_, _) => dragBox = Rectangle.Empty;
        PB_Sprite.MouseMove += (_, e) =>
        {
            if (e.Button != MouseButtons.Left || dragBox == Rectangle.Empty || dragBox.Contains(e.Location))
                return;
            dragBox = Rectangle.Empty;
            DragOutPkh();
        };
    }

    private void DragOutPkh()
    {
        if (pkh == null)
            return;
        PkmUtil.DragOutPkh(PB_Sprite, pkh);
    }

    private Panel CreateCard(HomeGameDataFormat format)
    {
        var exported = PkhService.Export(pkh!, format);
        var card = new Panel { Size = new Size(88, 100), Margin = new Padding(4), Tag = format, BorderStyle = BorderStyle.FixedSingle, Cursor = Cursors.Hand };
        var pb = new PictureBox { Size = new Size(76, 68), Location = new Point(5, 4), SizeMode = PictureBoxSizeMode.Zoom, Tag = format };
        var label = new Label { Text = format.ToString(), AutoSize = false, TextAlign = ContentAlignment.MiddleCenter, Location = new Point(0, 74), Size = new Size(86, 22), Tag = format };
        pb.Image = exported != null ? PKMSprite.Render(exported) : null;
        card.Controls.Add(pb);
        card.Controls.Add(label);

        var tip = exported == null
            ? $"{format}: export failed"
            : $"{format}: {PkmUtil.GetDisplayName(exported)}\nClick to view, drag out to export as {exported.Extension}.";
        foreach (var c in new Control[] { card, pb, label })
        {
            toolTip1.SetToolTip(c, tip);
            c.Click += (_, _) => SelectVersion(format);
            c.MouseDown += (_, e) =>
            {
                var size = SystemInformation.DragSize;
                dragBox = e.Button == MouseButtons.Left ? new Rectangle(e.X - (size.Width / 2), e.Y - (size.Height / 2), size.Width, size.Height) : Rectangle.Empty;
            };
            c.MouseUp += (_, _) => dragBox = Rectangle.Empty;
            c.MouseMove += (_, e) =>
            {
                if (e.Button != MouseButtons.Left || dragBox == Rectangle.Empty || dragBox.Contains(e.Location))
                    return;
                dragBox = Rectangle.Empty;
                if (pkh != null && PkhService.Export(pkh, format) is { } pk)
                    PkmUtil.DragOut(card, pk);
            };
        }
        return card;
    }

    // Only the version detail panel changes; the main sprite keeps following the active save (RefreshMainSprite).
    private void SelectVersion(HomeGameDataFormat format)
    {
        selected = format;
        RefreshSelectedVersion();
        AutoUpdateCurrentHandler(); // rule 4: auto-judge OT/HT whenever the version selection changes
    }

    /// <summary>Rule 4 (auto Current Handler): only while the selected version is the source version
    /// (the block matching the PKH's origin game) is CurrentHandler judged against the main editor's
    /// save protagonist, using PKHeX's own predicates —
    /// OT side = TradeOT/BelongsTo in full: origin game + both raw IDs (表ID/里ID, the OT/Misc display
    /// pair is a lossless view of ID32) + OT gender + OT name all equal → handler = OT (0);
    /// HT side = IsHandlerSame (HT name+gender equal to the save's OT): the exact TradeHT case that
    /// sets handler = 1 while leaving HT fields untouched — the complementary TradeHT case would also
    /// rewrite HT name/lang/gender/friendship/memories, which is out of scope (CurrentHandler only).
    /// No evidence leaves the imported value untouched; PC9-read-only and no-version states are no-ops.</summary>
    private void AutoUpdateCurrentHandler()
    {
        if (loading || pkh == null || PkhService.HasPC9(pkh))
            return;
        if (selected == HomeGameDataFormat.None || selected != PkhService.GetOriginFormat(pkh.Version))
            return; // not viewing the source version — never touch the field
        var sav = saveProvider.SAV;
        byte? desired;
        if (pkh.Version == sav.Version && pkh.TID16 == sav.TID16 && pkh.SID16 == sav.SID16
            && pkh.OriginalTrainerGender == sav.Gender && pkh.OriginalTrainerName == sav.OT)
            desired = 0; // PKHeX BelongsTo → TradeOT concludes OT
        else if (!pkh.IsUntraded && pkh.HandlingTrainerName == sav.OT && pkh.HandlingTrainerGender == sav.Gender)
            desired = 1; // PKHeX IsHandlerSame → TradeHT concludes HT (no field rewrite needed)
        else
            desired = null; // neither side matches — no evidence, keep the imported value
        if (desired is not { } target || pkh.CurrentHandler == target)
            return;
        Edit(p => p.CurrentHandler = target, $"current handler ({(target == 0 ? "OT" : "HT")})");
    }

    // Reconstructs a missing version from whichever stored version is nearest, exactly like PKHeX does when
    // the main editor's HOME importer needs a version that was never deposited (TryCreate on PKH.ConvertToXX).
    private void B_CreateVersion_Click(object? sender, EventArgs e)
    {
        if (pkh == null || CB_CreateFormat.SelectedItem is not HomeGameDataFormat format)
            return;
        if (PkhService.GetVersions(pkh).Contains(format))
        {
            MessageBox.Show(this, $"{format} is already stored in this PKH.", BaseTitle, MessageBoxButtons.OK, MessageBoxIcon.Information);
            return;
        }

        var copy = PkhService.Copy(pkh);
        PKM? created;
        try { created = copy.ConvertToPKM(format); }
        catch (Exception ex)
        {
            MessageBox.Show(this, $"PKHeX could not reconstruct {format}: {ex.Message}", BaseTitle, MessageBoxButtons.OK, MessageBoxIcon.Error);
            return;
        }
        if (created == null)
        {
            MessageBox.Show(this, $"{format} is not reachable from the versions currently stored in this PKH.", BaseTitle, MessageBoxButtons.OK, MessageBoxIcon.Warning);
            return;
        }

        pkh = copy; // ConvertToPKM added the reconstructed block to this copy; adopt it.
        selected = format;
        dirty = true;
        L_Status.Text = $"Reconstructed {format} from the nearest stored version (met location/ball may have been remapped, as HOME does).";
        RefreshAll();
    }

    private void RefreshSelectedVersion()
    {
        foreach (Control c in FLP_Versions.Controls)
            c.BackColor = c.Tag is HomeGameDataFormat f && f == selected ? SystemColors.Highlight : SystemColors.Control;

        if (pkh == null || selected == HomeGameDataFormat.None || PkhService.GetVersionBlock(pkh, selected) is not { } block)
        {
            GB_VersionInfo.Text = "Version data";
            TB_VersionInfo.Text = pkh != null && PkhService.GetVersions(pkh).Count == 0 ? "This PKH has no game version data." : "";
            return;
        }

        // Reflect over the version's own data block: every stored field is listed without a
        // per-version field list (same approach as PkhService.DiffCore's GameDataCore loop).
        // The exported entity is metadata only (origin + context for the location tables) — PKHeX's
        // own conversion supplies both, so no format/version mapping table is maintained here.
        var sample = PkhService.Export(pkh, selected);
        GB_VersionInfo.Text = $"Version data: {selected}";
        var sb = new StringBuilder();
        var seen = new HashSet<string>();
        foreach (var pi in block.GetType().GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            if (!PkhService.IsStored(pi) || pi.PropertyType.IsByRefLike || !seen.Add(pi.Name))
                continue;
            sb.AppendLine($"{pi.Name}: {BlockValue(pi, block, sample)}");
        }
        TB_VersionInfo.Text = sb.ToString();
    }

    private static string BlockValue(PropertyInfo pi, object block, PKM? entity)
    {
        // Binary structures show their type instead of a hex dump.
        var type = pi.PropertyType;
        if (type.IsByRefLike || type == typeof(byte[]))
            return $"<{FriendlyTypeName(type)}>";

        object? value;
        try { value = pi.GetValue(block); }
        catch (Exception) { return "<error>"; }
        if (value == null)
            return "-";
        if (value is byte[])
            return $"<{FriendlyTypeName(type)}>";

        // Readable names from PKHeX's tables: locations keep the raw ID, ID fields show the name only.
        string rawText = value.ToString() ?? "-";
        if (value is 0 && PkhService.IsMoveProp(pi.Name))
            return "-"; // empty Move1..4 / RelearnMove1..4 slot
        if (PkhService.ReadableValue(pi.Name, rawText, entity) is { } name)
            return pi.Name is "MetLocation" or "EggLocation" ? $"{rawText} ({name})" : name;

        if (value is IFormattable f) // numbers culture-free, enums by name
            return f.ToString(null, CultureInfo.InvariantCulture) ?? "-";

        // Objects that don't override ToString would only print their type — show a type placeholder.
        var text = value.ToString() ?? "-";
        return value.GetType().GetMethod(nameof(ToString), Type.EmptyTypes)?.DeclaringType == typeof(object)
            ? $"<{FriendlyTypeName(value.GetType())}>"
            : text;
    }

    private static string FriendlyTypeName(Type type)
    {
        if (type.IsArray)
            return FriendlyTypeName(type.GetElementType()!) + "[]";
        if (!type.IsGenericType)
            return type.Name;
        var name = type.Name;
        name = name[..name.IndexOf('`', StringComparison.Ordinal)];
        return $"{name}<{string.Join(", ", type.GetGenericArguments().Select(FriendlyTypeName))}>";
    }

    #endregion

    #region Load / save

    private bool ConfirmDiscard()
    {
        if (!dirty)
            return true;
        return MessageBox.Show(this, "The current PKH has unsaved changes. Discard them?", BaseTitle, MessageBoxButtons.YesNo, MessageBoxIcon.Warning) == DialogResult.Yes;
    }

    private void SetPkh(PKH value, string? path, bool isDirty, string status)
    {
        pkh = value;
        filePath = path;
        dirty = isDirty;
        L_Status.Text = status;
        RefreshAll();
    }

    /// <summary>Opens <paramref name="path"/> after the usual unsaved-changes prompt. False = cancelled or failed.</summary>
    internal bool OpenFile(string path)
    {
        if (!ConfirmDiscard())
            return false;
        if (!PkhService.TryLoad(path, out var loaded, out var error))
        {
            MessageBox.Show(this, $"Unable to open \"{Path.GetFileName(path)}\": {error}", BaseTitle, MessageBoxButtons.OK, MessageBoxIcon.Warning);
            return false;
        }
        var note = PkhService.HasPC9(loaded) ? " Contains Champions (PC9) data: read-only in this version." : "";
        SetPkh(loaded, path, false, $"Opened {Path.GetFileName(path)}.{note}");
        return true;
    }

    // Read-only surface for the HOME window: the live PKH (never mutated by callers), the save's
    // generation (picks which stored version a box sprite shows) and the save (box wallpaper).
    internal PKH? CurrentPkh => pkh;
    internal Type EditorPkmType => saveProvider.SAV.PKMType;
    internal SaveFile ActiveSave => saveProvider.SAV;

    private bool Save()
    {
        if (pkh == null)
            return false;
        using var dlg = new SaveFileDialog
        {
            Filter = "HOME data (*.pkh)|*.pkh|All files (*.*)|*.*",
            FileName = filePath != null ? Path.GetFileName(filePath) : PathUtil.CleanFileName($"{PkhService.GetDefaultFileName(pkh)}.pkh"),
            InitialDirectory = filePath != null ? Path.GetDirectoryName(filePath) : null,
        };
        if (dlg.ShowDialog(this) != DialogResult.OK)
            return false;
        if (!PkhService.TrySave(pkh, dlg.FileName, out var error))
        {
            MessageBox.Show(this, $"Save failed: {error}", BaseTitle, MessageBoxButtons.OK, MessageBoxIcon.Error);
            return false;
        }
        filePath = dlg.FileName;
        dirty = false;
        L_Status.Text = $"Saved {Path.GetFileName(filePath)} (verified readable by PKHeX).";
        UpdateTitle();
        return true;
    }

    private void B_Save_Click(object? sender, EventArgs e)
    {
        if (pkh != null)
            Save();
    }

    // "Close file": drop the current PKH and return to the freshly opened window state.
    private void B_CloseFile_Click(object? sender, EventArgs e)
    {
        if (pkh == null || !ConfirmDiscard())
            return;
        pkh = null;
        filePath = null;
        dirty = false;
        selected = HomeGameDataFormat.None;
        toolTip1.SetToolTip(L_Status, ""); // drop the last import report tooltip
        L_Status.Text = InitialStatus;
        RefreshAll(); // clears every field, the sprite and the version cards; also disables Save/Close
    }

    private void PKHEditor_FormClosing(object? sender, FormClosingEventArgs e)
    {
        if (!dirty)
            return;
        var answer = MessageBox.Show(this, "Save changes to the PKH before closing?", BaseTitle, MessageBoxButtons.YesNoCancel, MessageBoxIcon.Question);
        if (answer == DialogResult.Cancel || (answer == DialogResult.Yes && !Save()))
            e.Cancel = true;
    }

    #endregion

    #region Import

    // One plain (owner-less) Compare window per click — no singleton, so several can be open at
    // once; open windows are tracked only so RefreshNames can reach them all.
    private readonly List<FormDiff> compareForms = [];

    internal void ShowCompareWindow(PKM left, PKM right)
    {
        var form = new FormDiff(edit, saveProvider);
        form.FormClosed += (_, _) => compareForms.Remove(form);
        compareForms.Add(form);
        form.SetEntities(left, right);
        form.Show();
        form.Activate();
    }

    /// <summary>Left side for Compare: the PKH's data in the incoming format, else the first version the
    /// PKH actually stores. Export() would synthesize a missing block from core data, so membership in
    /// GetVersions is checked first (missing version → fall back, never fabricate).</summary>
    private static PKM? GetCompareLeft(PKH current, PKM incoming)
    {
        var target = PKH.GetType(incoming is PK7 ? typeof(PK8) : incoming.GetType());
        var versions = PkhService.GetVersions(current);
        if (target != HomeGameDataFormat.None && versions.Contains(target) && PkhService.Export(current, target) is { } same)
            return same;
        return versions.Count > 0 && PkhService.Export(current, versions[0]) is { } first ? first : null;
    }

    private void ImportPkm(PKM pk, string source)
    {
        if (pkh == null)
        {
            CreateFrom(pk, source);
            return;
        }

        var plan = PkhService.PlanImport(pkh, pk, CHK_UseCustomTracker.Checked);
        // Original gate kept below for easy revert: pure PKHeX conversions were applied directly,
        // with the report only in the status tooltip. AlwaysShowImportDialog short-circuits it now.
        bool discardItem = false;
        var compareLeft = GetCompareLeft(pkh, pk);
        if ((AlwaysShowImportDialog || plan.IsBlocked || plan.NeedsConfirm)
            && !ImportReportDialog.Confirm(this, plan, $"Import {pk.GetType().Name} from {source}", Font, compareLeft, left => ShowCompareWindow(left, pk), pk.HeldItem != 0, out discardItem))
        {
            L_Status.Text = "Import cancelled.";
            return;
        }
        if (plan.IsBlocked)
            return;
        toolTip1.SetToolTip(L_Status, string.Join(Environment.NewLine, plan.Items.Select(i => $"[{i.Group}] {i.Text}")));

        // The PKH never keeps the incoming item (Core.CopyFrom skips HeldItem): return it to the bag
        // unless the dialog's "Don't return item" was chosen — on failure the user picks cancel/continue.
        string bagNote = "";
        if (pk.HeldItem != 0 && !discardItem)
        {
            if (PkhService.TryReturnItemToBag(saveProvider.SAV, pk, out var bagItem))
            {
                bagNote = $" Held item {bagItem} returned to the bag.";
            }
            else if (!ConfirmImportWithoutItem(bagItem))
            {
                L_Status.Text = "Import cancelled.";
                return;
            }
            // Continue: the failed attempt left the save untouched, the item simply isn't recovered.
        }

        var target = PKH.GetType(pk is PK7 ? typeof(PK8) : pk.GetType());
        pkh = plan.Result;
        if (target != HomeGameDataFormat.None)
            selected = target;
        dirty = true;
        L_Status.Text = $"Imported {pk.GetType().Name} from {source}.{bagNote}";
        RefreshAll();
    }

    private void CreateFrom(PKM pk, string source)
    {
        PKH created;
        bool generated;
        try
        {
            created = PkhService.Create(pk, CHK_UseCustomTracker.Checked, out generated);
        }
        catch (Exception ex)
        {
            MessageBox.Show(this, $"PKHeX could not create a PKH from this {pk.GetType().Name}: {ex.Message}", BaseTitle, MessageBoxButtons.OK, MessageBoxIcon.Error);
            return;
        }

        var note = generated
            ? $" No HOME tracker: generated {created.Tracker:X16}."
            : created.Tracker != 0 ? $" HOME tracker {created.Tracker:X16} kept." : " No HOME tracker (custom tracker off).";
        if (PKH.GetType(pk is PK7 ? typeof(PK8) : pk.GetType()) == HomeGameDataFormat.None && pk is not PK7)
            note += $" {pk.GetType().Name} has no HOME version data; only shared data was stored.";

        // No PKH is loaded yet: never touch the bag here. The source PKM stays intact, so dropping
        // the same file again after this import runs the normal return-item flow against the new PKH.
        string bagNote = pk.HeldItem != 0
            ? " Held item was not returned — drop the same PKM again to send it to the bag."
            : "";
        SetPkh(created, null, true, $"Created PKH from {pk.GetType().Name} ({source}).{note}{bagNote}");
    }

    /// <summary>Shown when the held item couldn't reach the bag: true = import anyway without the item.</summary>
    private bool ConfirmImportWithoutItem(string reason) =>
        MessageBox.Show(this,
            $"The held item could not be returned to the bag ({reason}).{Environment.NewLine}{Environment.NewLine}" +
            "Continue the import anyway? The item will not be stored in the PKH. (Yes = import anyway, No = cancel)",
            BaseTitle, MessageBoxButtons.YesNo, MessageBoxIcon.Warning, MessageBoxDefaultButton.Button2) == DialogResult.Yes;

    #endregion

    #region Drag & drop

    private void OnDragEnter(object? sender, DragEventArgs e)
    {
        bool accept = e.Data?.GetDataPresent(DataFormats.FileDrop) == true && e.AllowedEffect.HasFlag(DragDropEffects.Copy);
        // Must be Copy: PKHeX's box slots treat Link as "moved to another slot".
        e.Effect = accept ? DragDropEffects.Copy : DragDropEffects.None;
    }

    private void OnDragDrop(object? sender, DragEventArgs e)
    {
        if (e.Data?.GetData(DataFormats.FileDrop) is not string[] { Length: not 0 } files)
            return;
        // Defer so the drag source (a PKHeX slot) is released before any dialog opens.
        var path = files[0];
        BeginInvoke(() => HandleDroppedFile(path));
    }

    private void HandleDroppedFile(string path)
    {
        if (PkhService.TryLoad(path, out _, out _))
        {
            OpenFile(path);
            return;
        }
        if (!PkmUtil.TryLoadPkm(path, saveProvider.SAV, out var pk, out var error))
        {
            MessageBox.Show(this, $"Unable to load \"{Path.GetFileName(path)}\": {error}", BaseTitle, MessageBoxButtons.OK, MessageBoxIcon.Warning);
            return;
        }
        ImportPkm(pk, Path.GetFileName(path));
    }

    #endregion

    #region Editing

    private void Edit(Action<PKH> change, string what)
    {
        if (loading || pkh == null || PkhService.HasPC9(pkh))
            return;
        change(pkh);
        dirty = true;
        L_Status.Text = $"Edited {what}.";
        RefreshAll();
    }

    private void TB_Nickname_Validated(object? sender, EventArgs e)
    {
        if (pkh == null || TB_Nickname.Text == pkh.Nickname)
            return;
        Edit(p =>
        {
            p.Nickname = TB_Nickname.Text;
            p.IsNicknamed = !string.IsNullOrEmpty(TB_Nickname.Text);
        }, "nickname");
    }

    private void NUD_EXP_ValueChanged(object? sender, EventArgs e)
    {
        if (pkh == null || (uint)NUD_EXP.Value == pkh.EXP)
            return;
        // RefreshAll recomputes the Level NUD from CurrentLevel — one edit, both fields in sync.
        Edit(p => p.EXP = (uint)NUD_EXP.Value, "EXP");
    }

    // EXP ↔ Level linkage: level changes write the EXP threshold for that level (clamped 1..100 by
    // the NUD bounds), EXP changes re-derive the level. Growth rate comes from the personal info.
    private void NUD_Level_ValueChanged(object? sender, EventArgs e)
    {
        if (loading || pkh == null || (byte)NUD_Level.Value == pkh.CurrentLevel)
            return;
        byte level = (byte)NUD_Level.Value;
        uint exp;
        try { exp = Experience.GetEXP(level, pkh.PersonalInfo.EXPGrowth); }
        catch (Exception) { return; } // no personal entry for species/form — keep the old EXP
        Edit(p => p.EXP = exp, $"level {level}");
    }

    private void CB_Gender_SelectionChangeCommitted(object? sender, EventArgs e)
    {
        // Items are ♂/♀/- in Gender-byte order (0/1/2); out-of-range values show as no selection.
        if (loading || pkh == null || CB_Gender.SelectedIndex is < 0 or > 2 || (byte)CB_Gender.SelectedIndex == pkh.Gender)
            return;
        byte gender = (byte)CB_Gender.SelectedIndex;
        Edit(p => p.Gender = gender, "gender");
    }

    private void CB_StatAlignment_SelectionChangeCommitted(object? sender, EventArgs e)
    {
        // StatAlignment is stored as a Nature value; same index-is-enum rule as CB_Nature.
        if (loading || pkh == null || (uint)CB_StatAlignment.SelectedIndex > (uint)Nature.Quirky || (Nature)CB_StatAlignment.SelectedIndex == pkh.StatAlignment)
            return;
        var n = (Nature)CB_StatAlignment.SelectedIndex;
        Edit(p => p.StatAlignment = n, "stat alignment");
    }

    private void CB_Nature_SelectionChangeCommitted(object? sender, EventArgs e)
    {
        // Items are localized strings built in enum order, so the selected index is the Nature value.
        if (pkh == null || (uint)CB_Nature.SelectedIndex > (uint)Nature.Quirky || (Nature)CB_Nature.SelectedIndex == pkh.Nature)
            return;
        var n = (Nature)CB_Nature.SelectedIndex;
        Edit(p => p.Nature = n, "nature");
    }

    private void NUD_Friendship_ValueChanged(object? sender, EventArgs e)
    {
        if (pkh == null || (byte)NUD_Friendship.Value == pkh.CurrentFriendship)
            return;
        Edit(p => p.CurrentFriendship = (byte)NUD_Friendship.Value, "friendship");
    }

    private void TB_Tracker_Validated(object? sender, EventArgs e)
    {
        if (pkh == null)
            return;
        if (!ulong.TryParse(TB_Tracker.Text.Trim(), NumberStyles.HexNumber, CultureInfo.InvariantCulture, out var value))
        {
            TB_Tracker.Text = pkh.Tracker.ToString("X16");
            return;
        }
        if (value != pkh.Tracker)
            Edit(p => p.Tracker = value, "HOME tracker");
    }

    private void B_NewTracker_Click(object? sender, EventArgs e)
    {
        if (pkh == null)
            return;
        if (pkh.Tracker != 0 && !PkhService.IsGeneratedTracker(pkh.Tracker)
            && MessageBox.Show(this, $"Replace the HOME-assigned tracker {pkh.Tracker:X16} with a generated one?", BaseTitle, MessageBoxButtons.YesNo, MessageBoxIcon.Warning) != DialogResult.Yes)
        {
            return;
        }
        // A new tracker on an existing PKH makes future imports look like a different Pokémon (see GetIdentity).
        if (PkhService.GetVersions(pkh).Count != 0
            && MessageBox.Show(this, "This PKH already has exported version data. Changing the tracker may make future PKM imports look like a different Pokémon. Continue?", BaseTitle, MessageBoxButtons.YesNo, MessageBoxIcon.Warning) != DialogResult.Yes)
        {
            return;
        }
        Edit(p => p.Tracker = PkhService.NewTracker(), "HOME tracker");
    }

    private void B_ClearTracker_Click(object? sender, EventArgs e)
    {
        if (pkh == null)
            return;
        if (pkh.Tracker != 0
            && MessageBox.Show(this, $"Clear the HOME tracker {pkh.Tracker:X16}? It will be set to 0.", BaseTitle, MessageBoxButtons.YesNo, MessageBoxIcon.Warning) != DialogResult.Yes)
        {
            return;
        }
        Edit(p => p.Tracker = 0, "HOME tracker");
    }

    // Persist the mode in the HOME metadata file, then re-evaluate the Gen button (and anything else gated on it).
    private void CHK_UseCustomTracker_CheckedChanged(object? sender, EventArgs e)
    {
        HomeStorage.SetUseCustomTracker(CHK_UseCustomTracker.Checked);
        RefreshAll();
    }

    #endregion

    #region Home

    private void B_Home_Click(object? sender, EventArgs e)
    {
        if (homeForm is null || homeForm.IsDisposed)
            homeForm = new HomeForm(this) { Owner = this }; // owned, so it closes with this editor
        homeForm.Show();
        homeForm.Activate();
    }

    /// <summary>Keeps this window's notion of the open file in step when the HOME window renames it
    /// (an overwrite save gives the file the standard name for the PKH it now holds).</summary>
    internal void RetargetFile(string oldPath, string newPath)
    {
        if (filePath == null || !string.Equals(filePath, oldPath, StringComparison.OrdinalIgnoreCase))
            return;
        filePath = newPath;
        UpdateTitle();
    }

    #endregion

    /// <summary>Re-applies names after PKHeX switches display language.</summary>
    public void RefreshNames()
    {
        RefreshAll();
        HomeForm.RefreshAllNames(); // slot tooltips carry localized names from the GameInfo tables
        foreach (var form in compareForms)
            form.RefreshNames();
    }
}
